# Generated by Django 4.1 on 2022-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('kill', models.IntegerField()),
                ('headkill', models.IntegerField()),
                ('longestkill', models.FloatField()),
                ('loadkill', models.IntegerField()),
                ('teamkill', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('damagedealt', models.FloatField()),
                ('damagetaken', models.FloatField()),
                ('dbno', models.IntegerField()),
                ('revive', models.IntegerField()),
                ('walkdistance', models.FloatField()),
                ('ridedistance', models.FloatField()),
                ('swimdistance', models.FloatField()),
                ('distance', models.FloatField()),
                ('boost', models.IntegerField()),
                ('heal', models.IntegerField()),
                ('deathtype', models.CharField(max_length=50)),
                ('acquired', models.IntegerField()),
                ('team_member', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=50)),
                ('team_kill', models.IntegerField()),
                ('team_assist', models.IntegerField()),
                ('team_distance', models.FloatField()),
                ('team_damagedealt', models.FloatField()),
                ('team_damagetaken', models.FloatField()),
                ('team_timesurvived', models.FloatField()),
                ('timesurvived', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('vehicle_destroys', models.IntegerField()),
                ('map_name', models.CharField(max_length=50)),
                ('game_duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PgcList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('tournament_type', models.CharField(max_length=50)),
                ('create_date', models.CharField(max_length=50)),
            ],
        ),
    ]
